import { useState, useEffect, useRef } from 'react';
import API_BASE from '../../lib/api';
import { useAuth } from '../../contexts/AuthContext';
import { MessageSquareWarning, Plus, CheckCircle, Clock, FileText, FileDown, X } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export function EmployeeComplaints() {
  const { user } = useAuth();
  const [complaints, setComplaints] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('Active'); // Active or Resolved
  const [showToast, setShowToast] = useState(null);
  const prevComplaintsRef = useRef([]);
  
  // Modal states
  const [isNewModalOpen, setIsNewModalOpen] = useState(false);
  const [subject, setSubject] = useState('');
  const [description, setDescription] = useState('');
  const [submitLoading, setSubmitLoading] = useState(false);
  const [error, setError] = useState('');
  
  const letterRef = useRef(null);

  const fetchComplaints = async (isPolling = false) => {
    try {
      const token = localStorage.getItem('dayflow_token');
      const response = await fetch(`${API_BASE}/api/data/complaints`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (response.ok) {
        const data = await response.json();
        
        // Check for newly resolved tickets if polling
        if (isPolling && prevComplaintsRef.current.length > 0) {
          data.forEach(newComp => {
            const oldComp = prevComplaintsRef.current.find(c => c._id === newComp._id);
            if (oldComp && oldComp.status !== 'Resolved' && newComp.status === 'Resolved') {
              setShowToast(`Ticket Resolved: ${newComp.subject}`);
              setTimeout(() => setShowToast(null), 5000);
            }
          });
        }
        
        prevComplaintsRef.current = data;
        setComplaints(data);
      }
    } catch (error) {
      console.error('Failed to load complaints:', error);
    } finally {
      if (!isPolling) setLoading(false);
    }
  };

  useEffect(() => {
    fetchComplaints();
    const interval = setInterval(() => {
      fetchComplaints(true);
    }, 5000); // Real-time polling
    return () => clearInterval(interval);
  }, []);

  const generatePDFLetter = () => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      pdf.setFontSize(22);
      pdf.setTextColor(80, 45, 85); // #502D55
      pdf.text('Odoo India HRMS', 20, 30);
      
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text('Official Employee Complaint Record', 20, 40);
      
      pdf.setDrawColor(80, 45, 85);
      pdf.line(20, 45, 190, 45);

      pdf.setFontSize(11);
      pdf.setTextColor(50, 50, 50);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60);
      pdf.text(`Employee Name: ${user?.name || 'Unknown'}`, 20, 70);
      pdf.text(`Employee ID: ${user?.login_id || 'Unknown'}`, 20, 80);
      pdf.text(`Department: ${user?.department || 'N/A'}`, 20, 90);

      pdf.setFontSize(14);
      pdf.setTextColor(0, 0, 0);
      pdf.text(`Subject: ${subject || 'N/A'}`, 20, 110);
      pdf.setDrawColor(200, 200, 200);
      pdf.line(20, 115, 190, 115);

      pdf.setFontSize(11);
      pdf.setTextColor(50, 50, 50);
      
      // Auto-wrap text
      const splitDesc = pdf.splitTextToSize(description || 'No description provided.', 170);
      pdf.text(splitDesc, 20, 130);

      pdf.setFontSize(9);
      pdf.setTextColor(150, 150, 150);
      pdf.text('This document is automatically generated by DayFlow HRMS.', 105, 280, { align: 'center' });

      return pdf.output('datauristring');
    } catch (error) {
      console.error("PDF generation failed", error);
      return null;
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!subject || !description) return setError('Subject and description are required.');
    
    setSubmitLoading(true);
    setError('');

    try {
      const generated_letter_url = await generatePDFLetter();
      
      // Also download the PDF immediately for the user
      if (generated_letter_url) {
        const a = document.createElement('a');
        a.href = generated_letter_url;
        a.download = `Complaint_Letter_${new Date().getTime()}.pdf`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      }
      
      const token = localStorage.getItem('dayflow_token');
      const response = await fetch(`${API_BASE}/api/data/complaints`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}` 
        },
        body: JSON.stringify({ subject, description, generated_letter_url })
      });

      if (!response.ok) throw new Error('Failed to submit ticket');
      
      setIsNewModalOpen(false);
      setSubject('');
      setDescription('');
      fetchComplaints();
    } catch (err) {
      setError(err.message);
    } finally {
      setSubmitLoading(false);
    }
  };

  if (loading) {
    return <div className="flex h-64 items-center justify-center">
      <div className="h-8 w-8 animate-spin rounded-full border-4 border-[#502D55] border-t-transparent"></div>
    </div>;
  }

  const getStatusColor = (status) => {
    switch(status) {
      case 'Resolved': return 'bg-green-100 text-green-700';
      case 'Rejected': return 'bg-red-100 text-red-700';
      case 'In Progress': return 'bg-blue-100 text-blue-700';
      default: return 'bg-yellow-100 text-yellow-700';
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="font-serif text-3xl font-bold text-gray-900">My Complaints & Tickets</h1>
          <p className="mt-1 text-sm text-gray-500">Raise issues or track your submitted tickets.</p>
        </div>
        <button 
          onClick={() => setIsNewModalOpen(true)}
          className="inline-flex items-center gap-2 bg-[#502D55] text-white px-5 py-2.5 rounded-xl font-medium shadow-md shadow-[#502D55]/20 hover:bg-[#935073] transition-colors"
        >
          <Plus size={20} />
          Raise New Ticket
        </button>
      </div>

      {showToast && (
        <div className="fixed top-20 right-6 z-50 animate-slide-in">
          <div className="rounded-lg bg-green-600 text-white px-5 py-3 text-sm shadow-lg flex items-center gap-2">
            <CheckCircle size={16} className="text-white" />{showToast}
          </div>
        </div>
      )}

      <div className="flex items-center gap-2 border-b border-gray-200">
        <button
          onClick={() => setActiveTab('Active')}
          className={`px-6 py-2.5 text-sm font-semibold rounded-t-lg transition-all ${
            activeTab === 'Active'
              ? 'bg-[#502D55] text-white shadow-sm'
              : 'bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900'
          }`}
        >
          Active Tickets
        </button>
        <button
          onClick={() => setActiveTab('Resolved')}
          className={`px-6 py-2.5 text-sm font-semibold rounded-t-lg transition-all ${
            activeTab === 'Resolved'
              ? 'bg-[#502D55] text-white shadow-sm'
              : 'bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900'
          }`}
        >
          Resolved Tickets
        </button>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        {(() => {
          const filtered = complaints.filter(c => activeTab === 'Resolved' ? c.status === 'Resolved' : c.status !== 'Resolved');
          if (filtered.length === 0) {
            return (
              <div className="p-12 text-center">
                <MessageSquareWarning className="mx-auto h-12 w-12 text-gray-300 mb-3" />
                <h3 className="text-lg font-medium text-gray-900">No {activeTab} Tickets</h3>
                <p className="mt-1 text-sm text-gray-500">You haven't raised any {activeTab.toLowerCase()} complaints or tickets.</p>
              </div>
            );
          }
          return (
            <div className="divide-y divide-gray-100">
              {filtered.map(complaint => (
                <div key={complaint._id} className="p-5 hover:bg-gray-50/50 transition-colors">
                  <div className="flex justify-between items-start mb-2">
                    <h3 className="font-semibold text-gray-900 text-lg">{complaint.subject}</h3>
                    <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${getStatusColor(complaint.status)}`}>
                      {complaint.status}
                    </span>
                  </div>
                  
                  <p className="text-sm text-gray-600 mb-3 whitespace-pre-wrap line-clamp-3">
                    {complaint.description}
                  </p>
                  
                  {complaint.admin_notes && (
                    <div className="bg-blue-50/50 rounded-lg p-3 border border-blue-100 mb-4">
                      <p className="text-xs font-semibold text-blue-800 mb-1">Admin Response:</p>
                      <p className="text-sm text-blue-900">{complaint.admin_notes}</p>
                    </div>
                  )}
                  
                  <div className="flex items-center gap-4 text-xs text-gray-500">
                    <div className="flex items-center gap-1">
                      <Clock size={14} />
                      {new Date(complaint.createdAt).toLocaleString()}
                    </div>
                    {complaint.generated_letter_url && (
                      <a 
                        href={complaint.generated_letter_url} 
                        download={`Complaint_${complaint._id}.pdf`}
                        className="flex items-center gap-1 text-[#502D55] hover:text-[#935073] font-medium transition-colors"
                      >
                        <FileDown size={14} />
                        Download PDF Letter
                      </a>
                    )}
                  </div>
                </div>
              ))}
            </div>
          );
        })()}
      </div>

      {/* New Ticket Modal */}
      {isNewModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in">
          <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-6 border-b border-gray-100 flex justify-between items-center">
              <h2 className="text-xl font-bold text-gray-900 font-serif">Raise a Ticket</h2>
              <button 
                onClick={() => setIsNewModalOpen(false)}
                className="text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X size={24} />
              </button>
            </div>
            
            <form onSubmit={handleSubmit} className="p-6 overflow-y-auto flex-1 space-y-5">
              {error && (
                <div className="p-3 bg-red-50 text-red-600 text-sm rounded-xl border border-red-100">
                  {error}
                </div>
              )}
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Subject</label>
                <input 
                  type="text" 
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="w-full p-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-[#502D55] focus:border-transparent outline-none"
                  placeholder="E.g., Issue with salary processing, Harassment report, etc."
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea 
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full p-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-[#502D55] focus:border-transparent outline-none h-32"
                  placeholder="Please describe the issue in detail..."
                />
              </div>

              {/* Hidden Template for PDF Generation removed, using native jsPDF now */}

              <div className="bg-blue-50 text-blue-800 p-4 rounded-xl flex gap-3 text-sm">
                <FileText className="flex-shrink-0 mt-0.5" size={18} />
                <p>An official PDF letter will be automatically generated and attached to this ticket based on your details.</p>
              </div>

              <div className="pt-4 flex justify-end gap-3">
                <button 
                  type="button"
                  onClick={() => setIsNewModalOpen(false)}
                  className="px-5 py-2.5 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-xl transition-colors"
                >
                  Cancel
                </button>
                <button 
                  type="submit"
                  disabled={submitLoading}
                  className="px-6 py-2.5 bg-[#502D55] text-white text-sm font-medium rounded-xl hover:bg-[#935073] shadow-md shadow-[#502D55]/20 transition-all flex items-center gap-2 disabled:opacity-70"
                >
                  {submitLoading ? (
                    <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"></div>
                  ) : (
                    <CheckCircle size={18} />
                  )}
                  Submit Ticket
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
