[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx vite build", "cd server && npm install"]

[start]
cmd = "NODE_ENV=production node server/server.js"
